#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/LogFunctions    # Tutorial log-file functions
#------------------------------------------------------------------------------

echo "--------"

# Remove old build/ directory
buildDir="$WM_PROJECT_DIR/build/${WM_OPTIONS}/${PWD##*/}"
if [ -d "$buildDir" ]
then
    echo "Removing old build directory: $buildDir" 1>&2
    rm -rf $buildDir
fi

removeLogs

echo "Cleaning tutorials ..."
foamCleanTutorials -self

# Remove arquivos do pós-processamento
echo "Removing post-processing files ..."
rm -f sampled_data.csv
rm -f myCloud_U_comparison.png
rm -f myCloud_U_ver_comparison.png
rm -f myCloud_wa_comparison.png
rm -f myCloud_wb_comparison.png
rm -f myCloud_Na_comparison.png
rm -f myCloud_Nb_comparison.png

# Remove diretório completo de pós-processamento (opcional)
if [ -d "postProcessing" ]
then
    echo "Removing postProcessing directory ..."
    rm -rf postProcessing
fi

echo "--------"

#------------------------------------------------------------------------------#
